# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'
  displayName: 'Download .env file from library'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: '**/.env'
    TargetFolder: $(Build.SourcesDirectory)/ai-hub
  displayName: 'Copy .env file to project source'

- script: |
    npm install
    npm install next

  displayName: 'Install npm'
  workingDirectory: '$(Build.SourcesDirectory)/ai-hub'
  
- script: |
    npx prisma db push --force-reset
    npx prisma generate

  displayName: 'Configure prisma'
  workingDirectory: '$(Build.SourcesDirectory)/ai-hub'

- script: |
    npm run test
  displayName: 'Unit testing with Jest'
  workingDirectory: '$(Build.SourcesDirectory)/ai-hub'

- script: |
    npm run build
  displayName: 'Build project'
  workingDirectory: '$(Build.SourcesDirectory)/ai-hub'
